### ISSUE TITLE
Questions on tutorial 2.1

### ISSUE THREAD

**Issue by jkanner** [gw-odw/odw-2022#2]
From Lupin:

Tuto 2.1
 
`ts = pycbc.noise.noise_from_psd(data_length*sample_rate, delta_t, psd, seed=127)`

>> Is there any reason to specify the seed with 127?
 
Can you explain why the expected SNR rises with mass, leaks, and then falls at high mass? (Challenge Q2)
I expect that the signal generated from the merger event with heavier masses can have larger power and induce a stronger signal.
But I cannot imagine why SNR falls at high mass (close to 200/200 ?).

**Comment by jkanner** [comment]
@linlupin   Using a seed should ensure that each noise realization will be identical, I think.  Of course, it should be OK to not use a seed, but by using it, we know that all students will see the same results.

Black holes with masses above 200 solar masses have a merger frequency that is too low for LIGO to detect.  This is due to the shape of the LIGO noise curve, which rises sharply at frequencies less than 30 Hz.  For black holes with a merger frequency less than about 30 Hz, the detected SNR goes down because LIGO is not sensitive in this region.

**Comment by linlupin** [comment]
Thanks for you to answer it. I have simulated the merger of IMBH case (BH mass of a few hundreds solar mass) and it does reflect what you mentioned in the response.
