### ISSUE TITLE
Questions on tutorial 3.2

### ISSUE THREAD

**Issue by jkanner** [gw-odw/odw-2022#3]
In 

`H1_psd = H1_psd_data.psd(fftlength=duration, overlap=0, window=("tukey", psd_alpha), method="median”)`

what’s the advantage to choose Turkey window?  Or is it just a randomly decision for the example?
 
 
Is there any benefit to determine the “reference_frequency=100” in the directory of argument in waveform? It seems that most examples in google pages use 50.

**Comment by jkanner** [comment]
@linlupin 

As far as I know, it is OK to use different windows for PSD estimation.  Actually, I've tended to use Blackman windows in the past, because I was told they minimize spectral leakage.  One advantage of Tukey windows is that they are very simple in the time-domain, so they are easy to understand.  

As far as I know, different choice of reference frequencies are OK when running PE jobs.  The main role of the reference frequency is to make definitions for the phase and other tricky parameters.  I think as long as the reference frequency matches when running the PE job and creating any waveforms using the posteriors, this is OK.

**Comment by linlupin** [comment]
I also assume that the reason to choose a specific window function is to minimize the spectral leakage. I found one web page (https://community.sw.siemens.com/s/article/window-types-hanning-flattop-uniform-tukey-and-exponential) to discuss such a phenomenon. Maybe we can provide it as a reference.
