### ISSUE TITLE
Rename Lightweight environment files? 

### ISSUE THREAD

**Issue by adivijaykumar** [gw-odw/odw-2022#8]
The lightweight environment file for linux is just called `environment.yml` right now. Should we be renaming this? Also, a note about the location of the lightweight environment files should be added into the "Setting up environments" page.

**Comment by jkanner** [comment]
No, we should not change the name of `evviornment.yml`.  That is a special name.  The `mybinder` application looks for a file with that name, and creates the software environment based on the contents.  

You are welcome to update the setup.md file as needed.

**Comment by adivijaykumar** [comment]
I see, thanks for that clarification! I will update the setup.md files.

**Comment by jkanner** [comment]
Thank you!
